# This workflow will do an install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Cache node_modules or restore if already cached
      uses: actions/cache@v3
      with:
        path: 'node_modules'
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-modules-${{ hashFiles('package-lock.json') }}
          
    - run: npm install && npm list
    
    - name: Get all changed *.js, *.ts & *.tsx file(s)
      id: changed-files
      uses: tj-actions/changed-files@v35
      with:
        files: |
          **/*.js
          **/*.ts
          **/*.tsx

    - name: What files where changed?
      run: |
        echo ${{ steps.changed-files.outputs.all_changed_and_modified_files }}

    - name: Run selective lint & full test (if pull request)
      run: npm run full-test-ci
      if: ${{ github.event_name == 'pull_request' }}
      env:
        CI: true
        FILES: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}

    - name: Run full lint & test (if pushing to master)
      run: npm run full-test
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      env:
        CI: true
